//go:build cgo && ((darwin && (amd64 || arm64)) || (linux && (amd64 || arm64) && (sidereon_use_system_lib || (sidereon_linux_glibc && !sidereon_linux_musl) || (sidereon_linux_musl && !sidereon_linux_glibc))) || (windows && amd64))

package native

/*
#include <sidereon.h>
*/
import "C"

const (
	OMMFormatKVNValue  uint32 = 0
	OMMFormatXMLValue  uint32 = 1
	OMMFormatJSONValue uint32 = 2

	BiasModeAbsoluteValue            = uint32(C.SIDEREON_BIAS_MODE_ABSOLUTE)
	BiasModeRelativeValue            = uint32(C.SIDEREON_BIAS_MODE_RELATIVE)
	BiasModeUnspecifiedValue         = uint32(C.SIDEREON_BIAS_MODE_UNSPECIFIED)
	BiasKindOSBValue                 = uint32(C.SIDEREON_BIAS_KIND_OSB)
	BiasKindDSBValue                 = uint32(C.SIDEREON_BIAS_KIND_DSB)
	BiasKindISBValue                 = uint32(C.SIDEREON_BIAS_KIND_ISB)
	BiasTargetSystemValue            = uint32(C.SIDEREON_BIAS_TARGET_KIND_SYSTEM)
	BiasTargetSatelliteValue         = uint32(C.SIDEREON_BIAS_TARGET_KIND_SATELLITE)
	BiasTargetReceiverValue          = uint32(C.SIDEREON_BIAS_TARGET_KIND_RECEIVER)
	BiasTargetSatelliteReceiverValue = uint32(C.SIDEREON_BIAS_TARGET_KIND_SATELLITE_RECEIVER)

	GNSSSystemGPS     = uint32(C.SIDEREON_GNSS_SYSTEM_GPS)
	GNSSSystemGLONASS = uint32(C.SIDEREON_GNSS_SYSTEM_GLONASS)
	GNSSSystemGalileo = uint32(C.SIDEREON_GNSS_SYSTEM_GALILEO)
	GNSSSystemBeiDou  = uint32(C.SIDEREON_GNSS_SYSTEM_BEI_DOU)
	GNSSSystemQZSS    = uint32(C.SIDEREON_GNSS_SYSTEM_QZSS)
	GNSSSystemNavIC   = uint32(C.SIDEREON_GNSS_SYSTEM_NAVIC)
	GNSSSystemSBAS    = uint32(C.SIDEREON_GNSS_SYSTEM_SBAS)

	CarrierBandL1  = uint32(C.SIDEREON_CARRIER_BAND_L1)
	CarrierBandL2  = uint32(C.SIDEREON_CARRIER_BAND_L2)
	CarrierBandL5  = uint32(C.SIDEREON_CARRIER_BAND_L5)
	CarrierBandE1  = uint32(C.SIDEREON_CARRIER_BAND_E1)
	CarrierBandE5A = uint32(C.SIDEREON_CARRIER_BAND_E5A)
	CarrierBandE5B = uint32(C.SIDEREON_CARRIER_BAND_E5B)
	CarrierBandE5  = uint32(C.SIDEREON_CARRIER_BAND_E5)
	CarrierBandE6  = uint32(C.SIDEREON_CARRIER_BAND_E6)
	CarrierBandB1C = uint32(C.SIDEREON_CARRIER_BAND_B1C)
	CarrierBandB1I = uint32(C.SIDEREON_CARRIER_BAND_B1I)
	CarrierBandB2A = uint32(C.SIDEREON_CARRIER_BAND_B2A)
	CarrierBandB2B = uint32(C.SIDEREON_CARRIER_BAND_B2B)
	CarrierBandB2  = uint32(C.SIDEREON_CARRIER_BAND_B2)
	CarrierBandB3I = uint32(C.SIDEREON_CARRIER_BAND_B3I)
	CarrierBandG1  = uint32(C.SIDEREON_CARRIER_BAND_G1)
	CarrierBandG2  = uint32(C.SIDEREON_CARRIER_BAND_G2)

	TimeScaleUTC      = uint32(C.SIDEREON_TIME_SCALE_UTC)
	TimeScaleTAI      = uint32(C.SIDEREON_TIME_SCALE_TAI)
	TimeScaleTT       = uint32(C.SIDEREON_TIME_SCALE_TT)
	TimeScaleTDB      = uint32(C.SIDEREON_TIME_SCALE_TDB)
	TimeScaleGPST     = uint32(C.SIDEREON_TIME_SCALE_GPST)
	TimeScaleGST      = uint32(C.SIDEREON_TIME_SCALE_GST)
	TimeScaleBDT      = uint32(C.SIDEREON_TIME_SCALE_BDT)
	TimeScaleGLONASST = uint32(C.SIDEREON_TIME_SCALE_GLONASST)
	TimeScaleQZSST    = uint32(C.SIDEREON_TIME_SCALE_QZSST)
	TimeScaleTCG      = uint32(C.SIDEREON_TIME_SCALE_TCG)
	TimeScaleTCB      = uint32(C.SIDEREON_TIME_SCALE_TCB)

	AllanSeriesPhaseSecondsValue                = uint32(C.SIDEREON_ALLAN_SERIES_KIND_PHASE_SECONDS)
	AllanSeriesFractionalFrequencyValue         = uint32(C.SIDEREON_ALLAN_SERIES_KIND_FRACTIONAL_FREQUENCY)
	AllanSeriesPhaseSecondsWithGapsValue        = uint32(C.SIDEREON_ALLAN_SERIES_KIND_PHASE_SECONDS_WITH_GAPS)
	AllanSeriesFractionalFrequencyWithGapsValue = uint32(C.SIDEREON_ALLAN_SERIES_KIND_FRACTIONAL_FREQUENCY_WITH_GAPS)
	AllanTauGridOctaveValue                     = uint32(C.SIDEREON_ALLAN_TAU_GRID_OCTAVE)
	AllanTauGridAllValue                        = uint32(C.SIDEREON_ALLAN_TAU_GRID_ALL)
	AllanTauGridExplicitValue                   = uint32(C.SIDEREON_ALLAN_TAU_GRID_EXPLICIT)
	GapPolicyRejectValue                        = uint32(C.SIDEREON_ALLAN_GAP_POLICY_REJECT)
	GapPolicyOmitTermsValue                     = uint32(C.SIDEREON_ALLAN_GAP_POLICY_OMIT_TERMS)
	AllanEstimatorADEVValue                     = uint32(C.SIDEREON_ALLAN_ESTIMATOR_ADEV)
	AllanEstimatorOverlappingADEVValue          = uint32(C.SIDEREON_ALLAN_ESTIMATOR_OVERLAPPING_ADEV)
	AllanEstimatorMDEVValue                     = uint32(C.SIDEREON_ALLAN_ESTIMATOR_MDEV)
	AllanEstimatorHDEVValue                     = uint32(C.SIDEREON_ALLAN_ESTIMATOR_HDEV)
	AllanEstimatorTDEVValue                     = uint32(C.SIDEREON_ALLAN_ESTIMATOR_TDEV)

	PowerLawRandomWalkFMValue       = uint32(C.SIDEREON_POWER_LAW_NOISE_TYPE_RANDOM_WALK_FM)
	PowerLawFlickerFMValue          = uint32(C.SIDEREON_POWER_LAW_NOISE_TYPE_FLICKER_FM)
	PowerLawWhiteFMValue            = uint32(C.SIDEREON_POWER_LAW_NOISE_TYPE_WHITE_FM)
	PowerLawFlickerPMValue          = uint32(C.SIDEREON_POWER_LAW_NOISE_TYPE_FLICKER_PM)
	PowerLawWhitePMValue            = uint32(C.SIDEREON_POWER_LAW_NOISE_TYPE_WHITE_PM)
	PowerLawOctaveUnderSampledValue = uint32(C.SIDEREON_POWER_LAW_OCTAVE_FLAG_UNDER_SAMPLED)
	PowerLawOctaveDegenerateValue   = uint32(C.SIDEREON_POWER_LAW_OCTAVE_FLAG_DEGENERATE_DEVIATION)
	PowerLawOctaveMissingMDEVValue  = uint32(C.SIDEREON_POWER_LAW_OCTAVE_FLAG_MISSING_MODIFIED_ALLAN)
	PowerLawDominantValue           = uint32(C.SIDEREON_POWER_LAW_OCTAVE_DOMINANCE_KIND_DOMINANT)
	PowerLawAmbiguousValue          = uint32(C.SIDEREON_POWER_LAW_OCTAVE_DOMINANCE_KIND_AMBIGUOUS)
	PowerLawFlaggedValue            = uint32(C.SIDEREON_POWER_LAW_OCTAVE_DOMINANCE_KIND_FLAGGED)

	TDMObservableRangeValue                = uint32(C.SIDEREON_TDM_OBSERVABLE_RANGE)
	TDMObservableDopplerInstantaneousValue = uint32(C.SIDEREON_TDM_OBSERVABLE_DOPPLER_INSTANTANEOUS)
	TDMObservableDopplerIntegratedValue    = uint32(C.SIDEREON_TDM_OBSERVABLE_DOPPLER_INTEGRATED)
	TDMObservableReceiveFrequencyValue     = uint32(C.SIDEREON_TDM_OBSERVABLE_RECEIVE_FREQ)
	TDMObservableTransmitFrequencyValue    = uint32(C.SIDEREON_TDM_OBSERVABLE_TRANSMIT_FREQ)
	TDMObservableTransmitRateValue         = uint32(C.SIDEREON_TDM_OBSERVABLE_TRANSMIT_FREQ_RATE)
	TDMObservableAngle1Value               = uint32(C.SIDEREON_TDM_OBSERVABLE_ANGLE1)
	TDMObservableAngle2Value               = uint32(C.SIDEREON_TDM_OBSERVABLE_ANGLE2)
	TDMObservableOtherValue                = uint32(C.SIDEREON_TDM_OBSERVABLE_OTHER)
	TDMUnitKilometersValue                 = uint32(C.SIDEREON_TDM_UNIT_KILOMETERS)
	TDMUnitSecondsValue                    = uint32(C.SIDEREON_TDM_UNIT_SECONDS)
	TDMUnitRangeUnitsValue                 = uint32(C.SIDEREON_TDM_UNIT_RANGE_UNITS)
	TDMUnitKilometersPerSecondValue        = uint32(C.SIDEREON_TDM_UNIT_KILOMETERS_PER_SECOND)
	TDMUnitHertzValue                      = uint32(C.SIDEREON_TDM_UNIT_HERTZ)
	TDMUnitHertzPerSecondValue             = uint32(C.SIDEREON_TDM_UNIT_HERTZ_PER_SECOND)
	TDMUnitDegreesValue                    = uint32(C.SIDEREON_TDM_UNIT_DEGREES)
	TDMUnitDecibelWattsValue               = uint32(C.SIDEREON_TDM_UNIT_DECIBEL_WATTS)
	TDMUnitDecibelHertzValue               = uint32(C.SIDEREON_TDM_UNIT_DECIBEL_HERTZ)
	TDMUnitSquareMetersValue               = uint32(C.SIDEREON_TDM_UNIT_SQUARE_METERS)
	TDMUnitMetersValue                     = uint32(C.SIDEREON_TDM_UNIT_METERS)
	TDMUnitSecondsPerSecondValue           = uint32(C.SIDEREON_TDM_UNIT_SECONDS_PER_SECOND)
	TDMUnitPercentValue                    = uint32(C.SIDEREON_TDM_UNIT_PERCENT)
	TDMUnitKelvinValue                     = uint32(C.SIDEREON_TDM_UNIT_KELVIN)
	TDMUnitHectopascalsValue               = uint32(C.SIDEREON_TDM_UNIT_HECTOPASCALS)
	TDMUnitTotalElectronContentUnitsValue  = uint32(C.SIDEREON_TDM_UNIT_TOTAL_ELECTRON_CONTENT_UNITS)
	TDMUnitDimensionlessValue              = uint32(C.SIDEREON_TDM_UNIT_DIMENSIONLESS)
	TDMUnitUnknownValue                    = uint32(C.SIDEREON_TDM_UNIT_UNKNOWN)
)
